version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=prod
      - APP_NAME=go-ssr-starter-front
      - PREFORK=false